DELETE http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzU3OTMxODY4LCJ1c2VySWQiOjF9.LeeXwfp1IVB9krGIWhS1wVLhrRlCrC6dCBHhKeeq310
